

userguide:
- title: "Getting things started"
  page: getting-started.html
- title: "Overview of a Vamonos visualization"
  page: overview.html
- title: "Implementing the algorithm for Vamonos"
  page: writing-algorithm.html
- title: "Core widgets"
  subpages:
    - title: "The controls widget"
      page: controls.html
    - title: "The pseudocode widget"
      page: pseudocode.html
    - title: "The call stack widget"
      page: callstack.html
- title: "Widgets for data structures"
  subpages:
    - title: "The array widget"
      page: array.html
    - title: "The graph widget"
      page: graph.html
- title: "Other widgets"
  page: other-widgets.html

